language: cpp
sudo: required

cache:
  directories:
    - $HOME/opt

addons:
  coverity_scan:
    project:
 
    build_command_prepend: "make clean"
    build_command:   "make"
    branch_pattern: coverity_scan

before_install:
  - export PATH=$(echo ${PATH} | awk -v RS=':' -v ORS=':' '/clang/ {next} {print}' | sed 's/:*$//')
  - APMDIR=$(pwd) && pushd .. && $APMDIR/Tools/scripts/configure-ci.sh && . ~/.profile && popd

script:
  - python Tools/autotest/param_metadata/param_parse.py
  - Tools/scripts/build_ci.sh

compiler: gcc

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "FjIwqZQV2FhNPWYITX5LZXTE38yYqBaQdbm3QmbEg/30wnPTm1ZOLIU7o/aSvX615ImR8kHoryvFPDQDWc6wWfqTEs3Ytq2kIvcIJS2Y5l/0PFfpWJoH5gRd6hDThnoi+1oVMLvj1+bhn4yFlCCQ2vT/jxoGfiQqqgvHtv4fLzI="
  matrix:
    - CI_BUILD_TARGET="minirevo"

